language: python
python: "3.6"
os:
  - linux
install:
  - pip install -r requirements.txt
stages:
  - test
  - name: publish
    if: branch = master
jobs:
  include:
    - stage: test
      script:
        - coverage run --source=pybricks test.py
        - coveralls
    - stage: publish
      script:
        - python3 pip install --user --upgrade setuptools wheel twine
        - sudo bash ./update.sh
