pr:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - tests/*
    - pybricks/*
    - setup.py
    - azure-pipelines.yml
    exclude:
    - .*
    - README.md
    - LICENSE

variables:
- group: pypi-credentials
- group: github-ssh-keys
- name: Branch
  value: '$(Build.SourceBranchName)'
- name: BuildNumber
  value: '$(Build.BuildNumber)'

jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python34:
        python.version: '3.4'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    displayName: 'Install dependencies'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        pip install pytest pytest-azurepipelines
        pytest
    displayName: 'pytest'

- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Test
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/pybricks'
      Contents: |
        *.py
        **\*.py
      TargetFolder: '$(Build.ArtifactStagingDirectory)/pybricks'
    displayName: 'Copy pybricks source'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)'
      Contents: |
        requirements.txt
        setup.py
        README.md
        LICENSE
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy requirements and setup'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'build'
      publishLocation: 'Container'

- job: BuildDocFiles
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Test
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/pybricks'
      Contents: |
        *.py
        **\*.py
      TargetFolder: '$(Build.ArtifactStagingDirectory)/pybricks'
    displayName: 'Copy pybricks source'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/docs'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/docs'
    displayName: 'Copy docs'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/examples'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/examples'
    displayName: 'Copy examples'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/template'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/template'
    displayName: 'Copy templates'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'build-docs'
      publishLocation: 'Container'

- deployment: Distribute
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Build
  environment: 'skeleton-$(Branch)'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            artifactName: 'build'
            buildType: 'current'
            downloadType: 'single'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: UsePythonVersion@0
          displayName: 'Use Python 3.7'
          inputs:
            versionSpec: 3.7
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: '$(System.ArtifactsDirectory)/build'
            script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
          displayName: 'Install Pip & Requirements'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: '$(System.ArtifactsDirectory)/build'
            script: |
              echo $PWD
              pip install --user --upgrade setuptools wheel twine
          displayName: 'Install Dist Packages'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: '$(System.ArtifactsDirectory)/build'
            script: |
              echo $PWD
              prefix=""
              if [ "$BRANCH" == "dev" ]
              then
                prefix="dev"
              fi
              build_number=${BUILD_NUMBER//./}
              export PACKAGE_BUILD=".${prefix}${build_number}"
              python setup.py sdist bdist_wheel
              python -m twine upload dist/* --skip-existing -u $PYPI_USERNAME -p $PYPI_PASSWORD
          displayName: 'Package and build'
          env:
            BRANCH: $(Branch)
            BUILD_NUMBER: $(BuildNumber)
            PYPI_USERNAME: $(PYPI_USERNAME)
            PYPI_PASSWORD: $(PYPI_PASSWORD)

- deployment: BuildDocs
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: BuildDocFiles
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
  environment: 'skeleton-docs-dev'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            artifactName: 'build-docs'
            buildType: 'current'
            downloadType: 'single'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: UsePythonVersion@0
          displayName: 'Use Python 3.7'
          inputs:
            versionSpec: 3.7
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: '$(System.ArtifactsDirectory)/build-docs'
            script: |
              python -m pip install --upgrade pip
              pip install -U Sphinx
              pip install sphinx_rtd_theme
              sphinx-build docs .
          displayName: 'Build Docs'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: '$(System.ArtifactsDirectory)/build-docs'
            script: |
              ssh-keyscan github.com >> ~/.ssh/known_hosts
          displayName: 'Add github host'
        - task: InstallSSHKey@0
          inputs:
            knownHostsEntry: github.com
            sshPublicKey: $(PublicKey)
            sshKeySecureFile: id_rsa_github
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: '$(System.ArtifactsDirectory)/build-docs'
            script: |
              git config --global user.name "Azure Pipeline"
              git config --global user.email "pipeline@azure.com"
              git init
              git checkout -b gh-pages
              git add .
              git commit -m "Build for $(BuildNumber)"
              git remote add origin git@github.com:KlutzyBubbles/lego-micropython-skeleton.git
              git push origin gh-pages
          displayName: 'Push to remote'
