from pybricks import ev3brick as brick
from pybricks.ev3devices import (Motor, TouchSensor, ColorSensor,
                                 InfraredSensor, UltrasonicSensor, GyroSensor)
from pybricks.parameters import (Port, Stop, Direction, Button, Color,
                                 SoundFile, ImageFile, Align)
from pybricks.tools import print, wait, StopWatch
from pybricks.robotics import DriveBase

brick.buttons()
brick.light(None)
brick.sound.beep(frequency=500, duration=100, volume=30)
brick.sound.beeps(5)
brick.sound.file(SoundFile.LEGO, volume=100)
brick.display.clear()
brick.display.text("text", coordinate=None)
brick.display.image(ImageFile.EV3, alignment=Align.CENTER, coordinate=None, clear=True)
brick.battery.voltage()
brick.battery.current()

motor = Motor(Port.A, direction=Direction.CLOCKWISE, gears=None)
motor.dc(100)
motor.angle()
motor.reset_angle(0)
motor.speed()
motor.stop(stop_type=Stop.COAST)
motor.run(100)
motor.run_time(100, 1000, stop_type=Stop.COAST, wait=True)
motor.run_angle(100, 360, stop_type=Stop.COAST, wait=True)
motor.run_target(100, 360, stop_type=Stop.COAST, wait=True)
motor.track_target(360)
motor.stalled()
motor.run_until_stalled(100, stop_type=Stop.COAST, duty_limit=100)
motor.set_dc_settings(100, 10)
motor.set_run_settings(100, 50)
motor.set_pid_settings(1, 2, 3, 1000, 360, 90, 90, 1000)

touch = TouchSensor(Port.S1)
touch.pressed()

color = ColorSensor(Port.S1)
color.color()
color.ambient()
color.reflection()
color.rgb()

infrared = InfraredSensor(Port.S1)
infrared.distance()
infrared.beacon(1)
infrared.buttons(1)

ultrasonic = UltrasonicSensor(Port.S1)
ultrasonic.distance(silent=False)
ultrasonic.presence()

gyro = GyroSensor(Port.S1, direction=Direction.CLOCKWISE)
gyro.speed()
gyro.angle()
gyro.reset_angle(0)

# print(repr())

print(repr(Port.A))
print(repr(Port.B))
print(repr(Port.C))
print(repr(Port.D))
print(repr(Port.S1))
print(repr(Port.S2))
print(repr(Port.S3))
print(repr(Port.S4))

print(repr(Direction.CLOCKWISE))
print(repr(Direction.COUNTCLOCKWISE))

print(repr(Stop.COAST))
print(repr(Stop.BRAKE))
print(repr(Stop.HOLD))

print(repr(Color.BLACK))
print(repr(Color.BLUE))
print(repr(Color.GREEN))
print(repr(Color.YELLOW))
print(repr(Color.RED))
print(repr(Color.WHITE))
print(repr(Color.BROWN))
print(repr(Color.ORANGE))
print(repr(Color.PURPLE))

print(repr(Button.LEFT_DOWN))
print(repr(Button.DOWN))
print(repr(Button.RIGHT_DOWN))
print(repr(Button.LEFT))
print(repr(Button.CENTER))
print(repr(Button.RIGHT))
print(repr(Button.LEFT_UP))
print(repr(Button.UP))
print(repr(Button.BEACON))
print(repr(Button.RIGHT_UP))

print(repr(Align.BOTTOM_LEFT))
print(repr(Align.BOTTOM))
print(repr(Align.BOTTOM_RIGHT))
print(repr(Align.LEFT))
print(repr(Align.CENTER))
print(repr(Align.RIGHT))
print(repr(Align.TOP_LEFT))
print(repr(Align.TOP))
print(repr(Align.TOP_RIGHT))

# IMAGE

print(repr(ImageFile.RIGHT))
print(repr(ImageFile.FORWARD))
print(repr(ImageFile.ACCEPT))
print(repr(ImageFile.QUESTION_MARK))
print(repr(ImageFile.STOP_1))
print(repr(ImageFile.LEFT))
print(repr(ImageFile.DECLINE))
print(repr(ImageFile.THUMBS_DOWN))
print(repr(ImageFile.BACKWARD))
print(repr(ImageFile.NO_GO))
print(repr(ImageFile.WARNING))
print(repr(ImageFile.STOP_2))
print(repr(ImageFile.THUMBS_UP))

print(repr(ImageFile.EV3))
print(repr(ImageFile.EV3_ICON))

print(repr(ImageFile.TARGET))

print(repr(ImageFile.BOTTOM_RIGHT))
print(repr(ImageFile.BOTTOM_LEFT))
print(repr(ImageFile.EVIL))
print(repr(ImageFile.CRAZY_2))
print(repr(ImageFile.KNOCKED_OUT))
print(repr(ImageFile.PINCHED_RIGHT))
print(repr(ImageFile.WINKING))
print(repr(ImageFile.DIZZY))
print(repr(ImageFile.DOWN))
print(repr(ImageFile.TIRED_MIDDLE))
print(repr(ImageFile.MIDDLE_RIGHT))
print(repr(ImageFile.SLEEPING))
print(repr(ImageFile.MIDDLE_LEFT))
print(repr(ImageFile.TIRED_RIGHT))
print(repr(ImageFile.PINCHED_LEFT))
print(repr(ImageFile.PINCHED_MIDDLE))
print(repr(ImageFile.CRAZY_1))
print(repr(ImageFile.NEUTRAL))
print(repr(ImageFile.AWAKE))
print(repr(ImageFile.UP))
print(repr(ImageFile.TIRED_LEFT))
print(repr(ImageFile.ANGRY))

# SOUND

print(repr(SoundFile.SHOUTING))
print(repr(SoundFile.CHEERING))
print(repr(SoundFile.CRYING))
print(repr(SoundFile.OUCH))
print(repr(SoundFile.LAUGHING_2))
print(repr(SoundFile.SNEEZING))
print(repr(SoundFile.SMACK))
print(repr(SoundFile.BOING))
print(repr(SoundFile.BOO))
print(repr(SoundFile.UH_OH))
print(repr(SoundFile.SNORING))
print(repr(SoundFile.KUNG_FU))
print(repr(SoundFile.FANFARE))
print(repr(SoundFile.CRUNCHING))
print(repr(SoundFile.MAGIC_WAND))
print(repr(SoundFile.LAUGHING_1))

print(repr(SoundFile.LEFT))
print(repr(SoundFile.BACKWARDS))
print(repr(SoundFile.RIGHT))
print(repr(SoundFile.OBJECT))
print(repr(SoundFile.COLOR))
print(repr(SoundFile.FLASHING))
print(repr(SoundFile.ERROR))
print(repr(SoundFile.ERROR_ALARM))
print(repr(SoundFile.DOWN))
print(repr(SoundFile.FORWARD))
print(repr(SoundFile.ACTIVATE))
print(repr(SoundFile.SEARCHING))
print(repr(SoundFile.TOUCH))
print(repr(SoundFile.UP))
print(repr(SoundFile.ANALYZE))
print(repr(SoundFile.STOP))
print(repr(SoundFile.DETECTED))
print(repr(SoundFile.TURN))
print(repr(SoundFile.START))

print(repr(SoundFile.MORNING))
print(repr(SoundFile.EV3))
print(repr(SoundFile.GO))
print(repr(SoundFile.GOOD_JOB))
print(repr(SoundFile.OKEY_DOKEY))
print(repr(SoundFile.GOOD))
print(repr(SoundFile.NO))
print(repr(SoundFile.THANK_YOU))
print(repr(SoundFile.YES))
print(repr(SoundFile.GAME_OVER))
print(repr(SoundFile.OKAY))
print(repr(SoundFile.SORRY))
print(repr(SoundFile.BRAVO))
print(repr(SoundFile.GOODBYE))
print(repr(SoundFile.HI))
print(repr(SoundFile.HELLO))
print(repr(SoundFile.MINDSTORMS))
print(repr(SoundFile.LEGO))
print(repr(SoundFile.FANTASTIC))

print(repr(SoundFile.SPEED_IDLE))
print(repr(SoundFile.SPEED_DOWN))
print(repr(SoundFile.SPEED_UP))

print(repr(SoundFile.BROWN))
print(repr(SoundFile.GREEN))
print(repr(SoundFile.BLACK))
print(repr(SoundFile.WHITE))
print(repr(SoundFile.RED))
print(repr(SoundFile.BLUE))
print(repr(SoundFile.YELLOW))

print(repr(SoundFile.TICK_TACK))
print(repr(SoundFile.HORN_1))
print(repr(SoundFile.BACKING_ALERT))
print(repr(SoundFile.MOTOR_IDLE))
print(repr(SoundFile.AIR_RELEASE))
print(repr(SoundFile.AIRBRAKE))
print(repr(SoundFile.RATCHET))
print(repr(SoundFile.MOTOR_STOP))
print(repr(SoundFile.HORN_2))
print(repr(SoundFile.LASER))
print(repr(SoundFile.SONAR))
print(repr(SoundFile.MOTOR_START))

print(repr(SoundFile.INSECT_BUZZ_2))
print(repr(SoundFile.ELEPHANT_CALL))
print(repr(SoundFile.SNAKE_HISS))
print(repr(SoundFile.DOG_BARK_2))
print(repr(SoundFile.DOG_WHINE))
print(repr(SoundFile.INSECT_BUZZ_1))
print(repr(SoundFile.DOG_SNIFF))
print(repr(SoundFile.T_REX_ROAR))
print(repr(SoundFile.INSECT_CHIRP))
print(repr(SoundFile.DOG_GROWL))
print(repr(SoundFile.SNAKE_RATTLE))
print(repr(SoundFile.DOG_BARK_1))
print(repr(SoundFile.CAT_PURR))

print(repr(SoundFile.ZERO))
print(repr(SoundFile.ONE))
print(repr(SoundFile.TWO))
print(repr(SoundFile.THREE))
print(repr(SoundFile.FOUR))
print(repr(SoundFile.FIVE))
print(repr(SoundFile.SIX))
print(repr(SoundFile.SEVEN))
print(repr(SoundFile.EIGHT))
print(repr(SoundFile.NINE))
print(repr(SoundFile.TEN))

print(repr(SoundFile.READY))
print(repr(SoundFile.CONFIRM))
print(repr(SoundFile.GENERAL_ALERT))
print(repr(SoundFile.CLICK))
print(repr(SoundFile.OVERPOWER))

wait(1000)

stopwatch = StopWatch()
stopwatch.time()
stopwatch.pause()
stopwatch.resume()
stopwatch.reset()

drive_base = DriveBase(motor, motor, 56, 112)
drive_base.drive(100, 50)
drive_base.drive_time(100, 50, 1000)
drive_base.stop(stop_type=Stop.COAST)
